In [6]:
#Data Vizualization :
import numpy as np
#list vs numpy time taken

from time import process_time
#importing process_time class from time

python_list=[i for i in range(10000)]  #1 to 10000 in python list
start_time=process_time() 
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time - start_time)    #time calculation for list 



0.0013832190000000466


In [7]:
np_array=np.array([i for i in range(10000)])  #we use array inbuilt function here
start_time=process_time()
np_array +=5
end_time=process_time()
print(end_time - start_time)    #time calculation for numpy   

#we can see that numpy takes less time in processing.. numpy takes less time!! 

0.0001321030000003276


In [8]:

#list
l1=[1,2,3,4,5]
print(l1)
type(l1)


[1, 2, 3, 4, 5]


list

In [9]:
#numpy array
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [10]:
#creating a 1 dim arrary
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [19]:
#creating 2 dim array
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print("\n")
b.shape  
#shows dimension of the array

[[1 2 3 4]
 [5 6 7 8]]




(2, 4)

In [20]:

c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float) #numpy array with float
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
