In [2]:
#create a numpy array with random values  #creating dataset randomly
import numpy as np
b=np.random.random((4,1))  #random random gives values between o to 1
print(b)


[[0.75404864]
 [0.70631832]
 [0.87374658]
 [0.2797514 ]]


In [4]:
d=np.linspace(10,30,5) #upper bound included
print(d)

[10. 15. 20. 25. 30.]


In [6]:
e=np.arange(10,30,5) #upper bound not included
print(e)

[10 15 20 25]


In [7]:
#convert a list to a numpy array
list1=[10,20,30,30,50]
np_array=np.array(list1)
print(np_array)
type(np_array)

[10 20 30 30 50]


numpy.ndarray

In [8]:
#analysing a numpy array
c=np.random.randint(10,20,(5,5))   #creating random values between given nos 10 and 20
print(c)                          

[[14 14 11 13 12]
 [15 12 11 18 16]
 [14 13 12 12 13]
 [17 14 10 13 19]
 [14 19 17 18 18]]


In [10]:
#list concatenation
l1=[1,2,3,4]
l2=['a','b','c']
print(l1+l2)

[1, 2, 3, 4, 'a', 'b', 'c']


In [15]:
#matrix calculation using numpy
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a/b)
print(a*b)

[[5 7 9]
 [0 2 8]
 [0 7 4]]
[[10 18 11]
 [16 17 17]
 [18 13 15]]
[[15 25 20]
 [16 19 25]
 [18 20 19]]
[[ -5 -11  -2]
 [-16 -15  -9]
 [-18  -6 -11]]
[[0.5        0.38888889 0.81818182]
 [0.         0.11764706 0.47058824]
 [0.         0.53846154 0.26666667]]
[[ 50 126  99]
 [  0  34 136]
 [  0  91  60]]


In [16]:
#another way to do matrix calculation in numpy
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 25 20]
 [16 19 25]
 [18 20 19]]
[[ -5 -11  -2]
 [-16 -15  -9]
 [-18  -6 -11]]
[[ 50 126  99]
 [  0  34 136]
 [  0  91  60]]
[[0.5        0.38888889 0.81818182]
 [0.         0.11764706 0.47058824]
 [0.         0.53846154 0.26666667]]


In [20]:
#transpose of matric using numpy 
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
print("\n")
trans=np.transpose(array)
print(trans)
print(trans.shape)  #2,3 matix chaned to 3,2 matrix rows and colums transposed

[[2 6 6]
 [2 1 9]]
(2, 3)


[[2 2]
 [6 1]
 [6 9]]
(3, 2)


In [21]:
#another method to transpose matrix
trans=array.T
print(trans)

[[2 2]
 [6 1]
 [6 9]]


In [27]:
#reshapping a new array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)
#reshaping the a array
print(a.reshape(3,2))

[[5 3 3]
 [4 7 3]]
(2, 3)
[[5 3]
 [3 4]
 [7 3]]


In [26]:
#reshaping a array by assigning it to b
b=a.reshape(3,2)
print(b)
print(b.shape)

[[1 5]
 [8 8]
 [7 4]]
(3, 2)
